CREATE TABLE brands (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company TEXT NOT NULL
);

ALTER TABLE foods
  ADD COLUMN
    brand TEXT references brands(name);

CREATE TABLE ingredients (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  impact INTEGER
);

ALTER TABLE foods
  ADD COLUMN
    i1 INTEGER NOT NULL references ingredients(id);

ALTER TABLE foods
  ADD COLUMN
    i2 INTEGER NOT NULL references ingredients(id);

ALTER TABLE foods
  ADD COLUMN
    i3 INTEGER NOT NULL references ingredients(id);

ALTER TABLE foods
  ADD COLUMN
    i4 INTEGER NOT NULL references ingredients(id);

ALTER TABLE foods
  ADD COLUMN
    i5 INTEGER NOT NULL references ingredients(id);


CREATE TABLE ratings (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  userId INTEGER NOT NULL references users(id),
  foodId INTEGER NOT NULL references foods(id) ON DELETE CASCADE,
  date_rated TIMESTAMP DEFAULT now() NOT NULL
);

ALTER TABLE foods
  ADD COLUMN
    rating INTEGER NOT NULL;